### ISSUE TITLE
什么时候能支持sql server？

### ISSUE THREAD

**Issue by jiafuzhang** [ivanceras/rustorm#23]
还是有一些系统使用sql server的，期待能尽快支持！兄弟加油↖(^ω^)↗

**Comment by jiafuzhang** [comment]
我自己顶一下

**Comment by ivanceras** [comment]
Hi, I can't speak chinese.

**Comment by jiafuzhang** [comment]
Oh My God!My English is not good. But I hope you can support Sql Server,please!

**Comment by jiafuzhang** [comment]
I have a old order system, that is using the Sql Server database. I want to use rust and rustorm to upgrade.Thank you!

**Comment by jiafuzhang** [comment]
↖(^ω^)↗

**Comment by ivanceras** [comment]
I can't find an MS SQL driver for rust for now, I have not been using MS SQL server ever since, so this is not a priority of this project. A more mature and heavily developed alternative of this project is https://github.com/sgrif/diesel, I believe they will come up with ms sql server support in the near future.

**Comment by jiafuzhang** [comment]
Thank you very much,I will always pay attention to and support your project.Hope that the project will become better and better.
