### ISSUE TITLE
Is rustorm dead?

### ISSUE THREAD

**Issue by dariusc93** [ivanceras/rustorm#32]
Im considering using pg for our backend db and noticed a few orm, one of which is rustorm. There have been no updates for the package and dont know if its dead, or what. Are there any updates in regards of the state of the project?

**Comment by ivanceras** [comment]
@dariusc93 It's not. I'm actually using it in one my of [big projects](https://github.com/ivanceras/curtain). I admit that rustorm is not very ergonomic for most users, since I'm using it to retrieve the metadata of the tables aside from its records, and building a CRUD app akin to PgAdminIII. If you really want to use this library, please take a look at [Query](https://github.com/ivanceras/rustorm/blob/master/src/query/mod.rs#L93) object. All queries can be expressed through it.

**Comment by Ygg01** [comment]
Isn't codegenta discontinued? How will this project move forward if its codegen is discontinued?

**Comment by ivanceras** [comment]
Rustorm can continue without codegenta. Codegenta's goal is already achieved with diesel, and the diesel project is far more ergonomic than codegenta. Rustorm will still move forward regardless of codegenta, since I'm using it in my big projects.
